import gensim.models.fasttext
from gensim.models.fasttext import FastText
import preprocesing
from pprint import pprint
from gensim.test.utils import datapath
import tempfile
import os
import nltk
import numpy as np
import pandas as pd
from IPython.display import display
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

if __name__ == "__main__":

    fucking_string = """ Sample Text 1 The article presents a prospective approach to increasing the working range of a sensing coil in magnetic resonance imaging via negative permeability structures.
The increase of the working range consists in improving the homogeneity of the RF magnetic field generated by the coil.
The homogeneity improvement is secured by a slab exhibiting a relatively high and negative effective permeability value.
This slab ensures a controlled concentration of magnetic flux into the coil's working area.
The approaches proposed to date have used slabs based on split-ring resonators assembled with lumped capacitors.
These approaches nevertheless limited by certain disadvantages, such as the potentially insufficient homogeneity of the resulting magnetic field or problematic selection of capacitors with an exact capacitance value.
In this context, the article discusses the Grid Quasi-Periodic Resonant structure as a novel concept.
The structure eliminates the need of lumped capacitances and offers a high filling factor on its surface area, which then results in considerable homogeneity of the influenced RF magnetic field.
The conceptual approach to the structure design and its working principle are both explained in the introductory section.
Further, the results of the numerical modeling of the structure are presented; these results indicate significant improvement of the magnetic field homogeneity in the selected area.
In order to verify the simulation results, a test structure was fabricated and experimentally measured on an automated measurement platform.
The relevant results are in good agreement with those obtained through the simulation.
The effective permeability of the structure is evaluated via processing of the measurement results.
The interaction between the structure and the phantom models was examined using numerical simulation; the obtained results indicate a significantly increased magnetic flux in the phantom and allow us to anticipate very good image improvement, which is to be a subject of further research.
Magnetic resonance (MR) is a widely used and continuously evolving measurement, spectroscopic, and imaging technique for the examination of various samples and objects (such as biological tissues or organic and inorganic materials) within medicine, material research, and characterization of technological substances.
The sample material subject to MR examination is characterized by its nuclear response to excitation by an external magnetic field, mainly in the radiofrequency (RF) domain.
The nuclear precession relaxation of matter provides a measurable signal further used for spectroscopy (MRS) and imaging (MRI) purposes or to measure physical properties of materials.
Various MR system parameters are carefully verified and controlled in order to obtain a high-quality response signal with a high signal-to-noise ratio (SNR).
In this connection, we can refer to, e.g., the static magnetic field strength and homogeneity, the excitation RF magnetic field strength and homogeneity, the quality factor of the resonator, or the resonator field filling factor.
The RF magnetic field homogeneity and magnitude are crucial factors.
The RF magnetic field is generated by an RF resonator, and its properties can be influenced by proper design.
The related scientific community has recently focused on new possibilities of modifying the RF magnetic field distribution inside resonators.
In this province, a major portion of the research effort has been directed towards the perspectives of translating the active region outside the resonator by means of elements which exhibit significant susceptibility at RF frequencies.
Another group of specialists then focuses on the improvement of the RF magnetic field distribution utilizing artificial material slabs; the goal is to increase the field magnitude in the examined object to step up the received signal and, consequently, to improve the MR image quality.
Generally, the electromagnetic (EM) field distribution in a given area can be adjusted using a material with a specific value of the dielectric constant (permittivity) r and permeabilityr.
Advances in electromagnetic theory have opened new horizons in the development of artificial materials, namely, metamaterials; these exhibit unconventional properties, such as negative values of the dielectric constant and permeability.
Metamaterials commonly consist of subwavelength elements, usually with resonant behavior.
From the perspective of MR applications, it is essential that these elements be made of materials with insignificant response to a static magnetic field; however, the elements can still exhibit a marked response in the RF domain, and if formed in a suitable configuration (for example, a slab), they are applicable for the adjustment of the RF magnetic field distribution.
A properly designed slab will ensure a controlled concentration of magnetic flux into the coil's working area and, consequently, an increase in the MR response signal.
A common method to set up a metamaterial slab exploits planar split-ring resonators (SRR) clustered in an array .
Such an array then comprises thin metal rings with interspaces, all deposited on a dielectric substrate.
The dimensions of particular resonators are substantially smaller than the operating wavelength.
Thus, the slab behaves as an artificial material exhibiting a specific effective permeability.
At frequencies used in MR, common split-ring resonators have to be assembled utilizing lumped capacitors; the reason lies in the relatively low working resonant frequency.
However, the approach involves certain disadvantages, including the potentially insufficient homogeneity of the resultant magnetic field or the need of lumped capacitors with mutually exact matched capacitance values.
Further, the technological tolerance of the capacitors impedes the achievement of the same resonant frequency in all the resonators, and major differences can occur despite careful selection of the capacitors.
Other complications comprise, for example, the non-uniform soldering of the capacitors, the capacitance temperature dependence, and the fact that even a small value of a capacitor’s material susceptibility can distort the resulting MR image.
Due to these issues, the development of resonators with only distributed parameters usable also at frequencies applied in MRI is of high importance; such an approach nevertheless requires a specific design to ensure a sufficient structure capacitance.
quasi-periodic resonator structures In order to avoid the above-described issues connected with lumped elements, we proposed, designed, and examined both theoretically (via a numerical analysis) and experimentally a quasi-periodic resonator (QPR) structure.
The developed structure has a relatively simple layout lacking lumped elements, and its resonant frequency can be adjusted from tens to hundreds of MHz.
In this context, it also has to be noted that the generated magnetic field exhibits very good homogeneity.
Since MR measurement techniques exploit the interaction of the matter via a magnetic field, we will now focus on analyzing the magnetic field component of the general EM field.
The basic QPR structure element is shown in Fig.
2.
The design is based on split-square resonators (SQR) periodically chained in a row.
The outer particular element has one side split, while all others exhibit two slits on their side edges.
The vector orientation of the excitation planar EM wave is shown also in Fig.
2.
The basic linear QPR structure element is designed as an electrically conductive layer on a dielectric substrate.
The basic QPR element was examined via a numerical finite element simulation in order to analyze the distribution of the generated magnetic field.
A FEM model was compiled for the structure compound of a Cu film with 35 m in thickness on a FR4 board with 0.2 mm in thickness.
The size of one square equaled 6 mm, with the line thickness of 0.5 mm, and five square elements were present in one row.
Fig.
3 shows the distribution of the normalized magnetic flux density Bn in the distance of 2 mm over the QPR structure at the resonant frequency; the gradient character of the magnetic flux density is evident from the representation.
The resultant gradient field pattern is caused by the effect where, in particular elements, the currents decrease from the left to the right.
The impedance of the first element is the lowest, whereas that of the second element is already higher; the impedance of the last element then shows the highest value.
The particular induced magnetic fields correspond to the magnitudes of the currents.
Although this gradient magnetic field can be used in specific applications, the creation of a homogeneous magnetic field is desired for standard MR imaging techniques.
The inhomogeneity of the generated magnetic field was solved using the design shown in Fig.
4, which demonstrates the new structure as a double-layered (or double) QPR using two linear QPR structures mutually rotated by 180 degrees and separated with a layer made of a dielectric substrate of a given thickness.
The model of the double QPR structure was simulated in the same manner as that of the basic linear structure, and the results can thus be directly compared.
The obtained result of the normalized magnetic flux density distribution over the double QPR structure is presented in Fig.
5.
The acquired magnetic field distribution now shows a rather homogeneous character.
When compared to the cross-sectional field distribution of common planar RF coils, the double QPR structure clearly radiates a magnetic field with considerable homogeneity.
Hence, this concept appears suitable for the RF field quality improvement in MR tomography.
The design of the above- described QPR and double QPR structures considers only excitation by a plane EM wave having a defined orientation with respect to the structure.
Then, the generated field pattern corresponds to the geometry of the structure.
Practically, it is necessary to create a magnetic field pattern suitably distributed in the given volume.
The attempt at creating a convenient magnetic field pattern was completed by the actual design of an enhanced structure.
The underlying concept is illustrated in Fig.
6.
The grid-like QPR consists of multiple double QPRs, where particular linear components are connected to form a grid structure; the behavior of the grid-like QPR structure was examined by means of a numerical analysis.
Instead of excitation by a planar wave, a single-loop coil was used as the source of the excitation EM field in order to approach the real application in MR techniques, where planar coils are often used.
The simulated structure comprises 5x5 cells, corresponding to the geometrical parameters mentioned above.
The structure was tuned at a resonant frequency very close to 200 MHz.
An excitation coil with the diameter of 5 mm was placed in parallel to the plane of the structure at the distance of 10 mm.
The results of the grid-like QPR analysis, namely, the magnetic field distribution over the structure, are shown in Fig.
7; it is obvious that the structure generates a non-homogeneous magnetic field if combined with the model of the coil.
This effect is caused by the fact that the electric field (as a part of the coil’s general EM field) is rotationally symmetrical with respect to the coil’s axis.
Hence, not all of the resonators are correctly aligned with the electric field direction, and only the resonators at the two outer side edges of the structure are properly excited.
In order to compensate for this effect, a system consisting of two double-layered, grid-like QPR structures was proposed.
A key point for this system is embodied in the fact that the two grid-like QPR structures are mutually rotated by 90 degrees; thus, a resulting four-layer resonant structure is formed.
The resultant RF magnetic field pattern originates from the superposition of particular RF magnetic fields radiated by the individual QPR structures.
The final structure is designated as the Grid Quasi-Periodic Structure (GQPR).
Fig.
8 shows a geometrical model to simulate the GQPR structure.
For the simulation, we used an excitation single-loop coil model with the diameter of 5 mm.
The distance between the coil and the GQPR was set to 10 mm.
The imaging cut plane for the magnetic field map visualization was in the distance of 2 mm from the GQPR.
Within the simulation, the distribution of the magnetic field in the imaging cut plane was evaluated.
The resultant field map is shown in Fig.
9; it is apparent that the actual configuration of the GQPR structure creates a considerably homogeneous magnetic field.
The results of the simulation have confirmed the presumptions related to the superposition of particular EM fields.
The above-presented simulation results showed that a properly configured GQPR structure can significantly enhance the active region of a planar MR RF coil.
When properly tuned, the GQPR structure behaves like a magnetically conductive medium, and we can thus attribute it to the effective permeability eff describing the effect of field magnitude increase in a given space.
The effective permeability can be defined as 	 ,	(1) where Bn1 is the normalized flux density over area S in the space containing only the excitation coil, and Bn2 is the normalized flux density over area S in the same space, where now both the excitation coil and the GQPR structure are present.
In order to calculate the effective permeability, it is necessary to perform two numerical analyses, one with and one without the studied structure.
The next step then consists in selecting the integration areas.
The results of ef for the GQPR are shown in Fig.
10; the minus sign represents the fact that the GQPR reverses the phase of the magnetic field.
We can consider the effective permeability as a field enhancement factor.
The results of the numerical analysis constitute a promising potential of enhancing the active range of MR RF coils.
An experimental examination of the GQPR structure was performed to verify the real behavior of the structure.
The investigation of the GQPR involved measuring the RF magnetic field distribution over the structure; the measurement setup scheme is shown in Fig.
11.
The excitation signal was provided by the RF signal generator feeding the transmitter.
The signal from the sensor was detected by a spectrum analyzer; the RF generator and the spectrum analyzer were in frequency synchronization.
The measured sample (the GQPR structure) was placed between the transmitter and the sensor.
A planar single loop coil with the diameter of 30 mm was used to act as the transmitter, as shown in Fig.
12a).
The coil was positioned at the distance of 10 mm from the measured structure.
To measure the field magnitude, we used a small single-loop pick-up coil, Fig.
12b).
The dimension of the sensing coil was kept very small (2 mm in diameter) to ensure a low inductance and to avoid distorted distribution of the measured field.
The pick-up coil was moved over the GQPR structure by means of an automated positioning platform, Fig.
13.
The experimental sample of the structure was fabricated as two boards made of FR4 laminate having the thickness of 0.1 mm and carrying 35 m copper layers on both sides, as shown in Fig.
14.
Each grid comprised 8x8 square elements with the side length of 8 mm.
The two boards were separated by a polyethylene foil of 0.1 mm in thickness.
The resonant frequency of the GQPR structure corresponded to 83 MHz.
The mapping of the RF magnetic field of the area with the dimension of 80x80 mm was conducted at several different heights over the GQPR, with the measurement step of 1 mm.
The measured data were used to visualize the magnetic field magnitude distribution.
Since the actual value of the field magnitude is a function of several factors, only the normalized value of the magnetic flux density is presented.
In order to compare the effect of the GQPR structure on the magnetic field distribution, the coil-induced field (without the GQPR) was measured as well.
The magnetic field distribution over the solitary coil at the distance of 2 mm is represented in Fig.
15.
It is obvious that the field achieves its maximum over the center of the coil and that it quickly decays in the space outside the coil.
Subsequently, the GQPR structure was placed between the excitation coil and the pick-up coil, and the field mapping was repeated.
The measured field distribution at the distance of 10 mm over the structure is shown in Fig.
16.
It is obvious that a magnetic field with good homogeneity has been created.
Fig.
17 shows the measured field distribution at the distance of 1 mm over the structure.
In this case, a local inhomogeneity is noticeable, which is caused by an incomplete superposition of particular fields in close proximity to the structure.
We also conducted an experiment with excitation at frequencies farther from the resonant frequency.
Fig.
18 presents a condition where the excitation frequency was higher than the resonant one; apparently, the field enhancement effect vanished.
When comparing the outcome of the structure simulation and the measured results, we can conclude that they are in a good match.
The slight differences are caused by two reasons, the first one being the finite size of the sensing pick-up coil, and secondly, the numerical model was located in the middle of the perfectly matched layers.
This latter condition then restrained the influence of reflected EM waves on the structure.
The presented results show that it is possible to design and fabricate a planar resonant structure with distributed parameters to enhance the RF magnetic field distribution in MRI.
As the use of lumped capacitors was eliminated, the set of problems including their precise selection, temperature stability, and the occurrence of artifacts could be entirely disregarded.
A novel Grid Quasi-Periodic Resonant structure was introduced, and the promising results of the related numerical modeling were verified by experimental measurement.
The outcome of the measurement is in good agreement with the simulation results."""

    # corpus_file = datapath('lee_background.cor')
    #
    # model = FastText(vector_size=100)
    #
    # model.build_vocab(corpus_file=corpus_file)
    #
    # model.train(corpus_file=corpus_file, epochs=model.epochs, total_examples=model.corpus_count, total_words=model.corpus_total_words)
    #
    # pprint(model)
    #
    # with tempfile.NamedTemporaryFile(prefix='saved_model_gensim', delete=False) as tmp:
    #     model.save(tmp.name, separately=[])
    #
    # loaded_model = FastText.load(tmp.name)
    # pprint(loaded_model)
    #
    # os.unlink(tmp.name)
    #
    # wv = model.wv
    # pprint(wv)
    # pprint('night' in wv.key_to_index)
    # pprint('nights' in wv.key_to_index)
    # pprint(wv['night'])
    # pprint(wv['nights'])
    #
    #

    doc = preprocesing.read_docx('Sample_text_1.docx', paragraph=True)


    # tokenized_text = preprocesing.word_tokenization(doc)
    tokenized_text = preprocesing.sentence_tokenization(doc)
    preprocesed_text = preprocesing.normalizace_textu(tokenized_text)
    print(preprocesed_text)
    df_norm = pd.DataFrame({'Document': preprocesed_text})

    text_file = open('preprocesd_text.txt', 'w')
    text_file.writelines('\n'.join(preprocesed_text))
    text_file.close()

    # corpus_file = gensim.models.word2vec.LineSentence('preprocesd_text.txt')
    # print(corpus_file)

    # corpus_file = datapath('lee_background.cor')
    # print(corpus_file)
    fasttext_model = gensim.models.fasttext.FastText(vector_size=100, window=50, min_count=5, sample=1e-3, sg=1, epochs=50)
    fasttext_model.build_vocab(corpus_file='preprocesd_text.txt')
    fasttext_model.train(corpus_file='preprocesd_text.txt', epochs=fasttext_model.epochs, total_examples=fasttext_model.corpus_count,
                 total_words=fasttext_model.corpus_total_words)
    input_words = ['fields', 'structure', 'magnetic', 'coil', 'result']
    print(fasttext_model)
    # print(fasttext_model.wv.most_similar('field', topn=5))
    similar_words = {search_term: [item[0] for item in fasttext_model.wv.most_similar(search_term, topn=5)] for search_term in input_words}

    print(similar_words)

    print(fasttext_model.wv.similarity(w1='field', w2='response'))
    print(fasttext_model.wv.similarity(w1='structure', w2='numerical'))

    unique_words = list(set([word for sublist in [doc.split() for doc in preprocesed_text] for word in sublist]))
    word_fasttext_vectors = np.array([fasttext_model.wv[word] for word in unique_words])


    tsne = TSNE(n_components=2, random_state=0, n_iter=5000, perplexity=3)
    np.set_printoptions(suppress=True)
    T = tsne.fit_transform(word_fasttext_vectors)
    labels = unique_words

    plt.figure(figsize=(12, 6))
    plt.scatter(T[:, 0], T[:, 1], c='orange', edgecolors='r')
    for label, x, y in zip(labels, T[:, 0], T[:, 1]): plt.annotate(label, xy=(x + 1, y + 1), xytext=(0, 0),
                                                                   textcoords='offset points')
    doc_fasttext_vector = np.array([fasttext_model.wv[doc] for doc in preprocesed_text])

    plt.show()