import pandas as pd

import preprocesing
import numpy as np

from numpy import dot
from numpy.linalg import norm
#from keras.preprocessing import text, sequence
#from keras.utils import np_utils




if __name__ == "__main__":
    a = "The sky is blue and beautiful. The quick brown fox jumps over the lazy dog. Love this blue and beautiful sky.  A king's breakfast has sausages, ham, bacon, eggs, toast and beans. I love green eggs, ham, sausages and bacon. The brown fox is quick and the blue dog is lazy. The sky is very blue and the sky is very beautiful today. The dog is lazy but the brown fox is quick."
    b = "It was so funny that I couldnt stop laughing really. "
    c = "WTF is going out here"

    norm = preprocesing.sentence_tokenization(a)
    norm = preprocesing.normalizace_textu(norm)
    norm = np.array(norm)
    df_norm = pd.DataFrame({'Document': norm})
    print("norm", norm)
    x = preprocesing.tf_idf_v(a, rm_stop_words=True)

    preprocesing.BOW(a, 10)

    print(type(norm))
    print("matice tf-idf")
    y = preprocesing.tf_idf_v(a)[0]
    yy = preprocesing.tf_idf_v(a)[2]
#   x = preprocesing.tf_idf_v(b)[0]
#   z = preprocesing.tf_idf_v(c)[0]
    print(yy)
    print("matice podobnosti")
    sm = preprocesing.tf_idf_cosine_similarity_single_doc(y)

# -------------------AHC------------------------------
    linkage_matrix = preprocesing.ahc(sm)
    preprocesing.ahc_dendrogram(linkage_matrix)
    preprocesing.use_of_fcluster(linkage_matrix, df_norm)

# -------------------------LDA------------------------
# potřeba matice z BOW
#    preprocesing.lda_model(preprocesing.BOW(a, 10, if_print=False)[0])

    preprocesing.lda_model(a)

    Text_for_similariy = """The increase of the working range consists in improving the homogeneity of the RF magnetic field generated by the coil.
Further, the results of the numerical modeling of the structure are presented; these results indicate significant improvement of the magnetic field homogeneity in the selected area.
In this connection, we can refer to, e.g., the static magnetic field strength and homogeneity, the excitation RF magnetic field strength and homogeneity, the quality factor of the resonator, or the resonator field filling factor.
The RF magnetic field homogeneity and magnitude are crucial factors.
The basic QPR structure element is shown in Fig.
The vector orientation of the excitation planar EM wave is shown also in Fig.
Fig.
3 shows the distribution of the normalized magnetic flux density Bn in the distance of 2 mm over the QPR structure at the resonant frequency; the gradient character of the magnetic flux density is evident from the representation.
The inhomogeneity of the generated magnetic field was solved using the design shown in Fig.
The obtained result of the normalized magnetic flux density distribution over the double QPR structure is presented in Fig.
When compared to the cross-sectional field distribution of common planar RF coils, the double QPR structure clearly radiates a magnetic field with considerable homogeneity.
The underlying concept is illustrated in Fig.
An excitation coil with the diameter of 5 mm was placed in parallel to the plane of the structure at the distance of 10 mm.
The results of the grid-like QPR analysis, namely, the magnetic field distribution over the structure, are shown in Fig.
The resultant RF magnetic field pattern originates from the superposition of particular RF magnetic fields radiated by the individual QPR structures.
Fig.
The distance between the coil and the GQPR was set to 10 mm.
The imaging cut plane for the magnetic field map visualization was in the distance of 2 mm from the GQPR.
The resultant field map is shown in Fig.
The results of ef for the GQPR are shown in Fig.
The investigation of the GQPR involved measuring the RF magnetic field distribution over the structure; the measurement setup scheme is shown in Fig.
A planar single loop coil with the diameter of 30 mm was used to act as the transmitter, as shown in Fig.
The coil was positioned at the distance of 10 mm from the measured structure.
To measure the field magnitude, we used a small single-loop pick-up coil, Fig.
The pick-up coil was moved over the GQPR structure by means of an automated positioning platform, Fig.
The mapping of the RF magnetic field of the area with the dimension of 80x80 mm was conducted at several different heights over the GQPR, with the measurement step of 1 mm.
The measured data were used to visualize the magnetic field magnitude distribution.
In order to compare the effect of the GQPR structure on the magnetic field distribution, the coil-induced field (without the GQPR) was measured as well.
The magnetic field distribution over the solitary coil at the distance of 2 mm is represented in Fig.
Subsequently, the GQPR structure was placed between the excitation coil and the pick-up coil, and the field mapping was repeated.
The measured field distribution at the distance of 10 mm over the structure is shown in Fig.
Fig.
17 shows the measured field distribution at the distance of 1 mm over the structure.
Fig.
The presented results show that it is possible to design and fabricate a planar resonant structure with distributed parameters to enhance the RF magnetic field distribution in MRI.
The increase of the working range consists in improving the homogeneity of the RF magnetic field generated by the coil.
The structure eliminates the need of lumped capacitances and offers a high filling factor on its surface area, which then results in considerable homogeneity of the influenced RF magnetic field.
Further, the results of the numerical modeling of the structure are presented; these results indicate significant improvement of the magnetic field homogeneity in the selected area.
In this connection, we can refer to, e.g., the static magnetic field strength and homogeneity, the excitation RF magnetic field strength and homogeneity, the quality factor of the resonator, or the resonator field filling factor.
From the perspective of MR applications, it is essential that these elements be made of materials with insignificant response to a static magnetic field; however, the elements can still exhibit a marked response in the RF domain, and if formed in a suitable configuration (for example, a slab), they are applicable for the adjustment of the RF magnetic field distribution.
The basic QPR structure element is shown in Fig.
The basic QPR element was examined via a numerical finite element simulation in order to analyze the distribution of the generated magnetic field.
Fig.
3 shows the distribution of the normalized magnetic flux density Bn in the distance of 2 mm over the QPR structure at the resonant frequency; the gradient character of the magnetic flux density is evident from the representation.
The inhomogeneity of the generated magnetic field was solved using the design shown in Fig.
The obtained result of the normalized magnetic flux density distribution over the double QPR structure is presented in Fig.
When compared to the cross-sectional field distribution of common planar RF coils, the double QPR structure clearly radiates a magnetic field with considerable homogeneity.
An excitation coil with the diameter of 5 mm was placed in parallel to the plane of the structure at the distance of 10 mm.
The results of the grid-like QPR analysis, namely, the magnetic field distribution over the structure, are shown in Fig.
The resultant RF magnetic field pattern originates from the superposition of particular RF magnetic fields radiated by the individual QPR structures.
Fig.
For the simulation, we used an excitation single-loop coil model with the diameter of 5 mm.
The distance between the coil and the GQPR was set to 10 mm.
The imaging cut plane for the magnetic field map visualization was in the distance of 2 mm from the GQPR.
The resultant field map is shown in Fig.
The above-presented simulation results showed that a properly configured GQPR structure can significantly enhance the active region of a planar MR RF coil.
The results of ef for the GQPR are shown in Fig.
The investigation of the GQPR involved measuring the RF magnetic field distribution over the structure; the measurement setup scheme is shown in Fig.
The coil was positioned at the distance of 10 mm from the measured structure.
To measure the field magnitude, we used a small single-loop pick-up coil, Fig.
The mapping of the RF magnetic field of the area with the dimension of 80x80 mm was conducted at several different heights over the GQPR, with the measurement step of 1 mm.
The measured data were used to visualize the magnetic field magnitude distribution.
In order to compare the effect of the GQPR structure on the magnetic field distribution, the coil-induced field (without the GQPR) was measured as well.
The magnetic field distribution over the solitary coil at the distance of 2 mm is represented in Fig.
Subsequently, the GQPR structure was placed between the excitation coil and the pick-up coil, and the field mapping was repeated.
The measured field distribution at the distance of 10 mm over the structure is shown in Fig.
Fig.
17 shows the measured field distribution at the distance of 1 mm over the structure.
Fig.
The presented results show that it is possible to design and fabricate a planar resonant structure with distributed parameters to enhance the RF magnetic field distribution in MRI.
"""
    print("Text similarity of text sumarization")
    preprocesd_text = preprocesing.tf_idf_v(Text_for_similariy)[0]
    print(preprocesing.sentence_tokenization(Text_for_similariy)[0])
    print(preprocesing.sentence_tokenization(Text_for_similariy)[35])
    similarity_matrix = preprocesing.tf_idf_cosine_similarity_single_doc(preprocesd_text)